services:
  app:
    container_name: gohub-ecommerce
    image: 533910826927.dkr.ecr.ap-southeast-1.amazonaws.com/gohub-ecommerce:dev-latest
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: $DB_PORT
      DB_PASSWORD: $DB_PASSWORD
      DB_USER: $DB_USER
      DB_NAME: $DB_NAME
    networks:
      - backend-network
    ports:
      - 3001:3000
    volumes:
      - ./media:/app/media
      - ./public:/app/public
      - ./themes:/app/themes

networks:
  backend-network:
    name: gohub-backend_default
    external: true
