services:
  app:
    build:
      dockerfile: ./Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: $DB_PORT
      DB_PASSWORD: $DB_PASSWORD
      DB_USER: $DB_USER
      DB_NAME: $DB_NAME
    networks:
      - backend-network
    ports:
      - 3001:3000
    volumes:
      - ./media:/app/media
      - ./public:/app/public
      - ./themes:/app/themes

networks:
  backend-network:
    name: backend-network
    external: true