const CLIENT_CODE = {
  OK: '000',
  INTERNAL_ERROR: '001',
  CART_ERROR: 'CART_001',
  COUPON_INVALID: 'COUPON_001',
  REFERRAL_COUPON_INVALID: 'REFERRAL_COUPON_INVALID'
}

module.exports = {
  CLIENT_CODE
}
